### ISSUE TITLE
[Bug]: OAuth error with plugin versions > 1.0.5

### ISSUE THREAD

**Issue by d11ahirst** [linode/packer-plugin-linode#129]
### Packer Version

v1.9.4

### Packer Plugin Linode Version

v1.1.3

### Expected Behavior

When building an image using plugin greater than 1.0.5 its failing using an existing token created a few years ago, i would expect the image to build successfully.

I am setting linode_token with a valid token that works in v1.0.5 if I go > than this version it fails

### Actual Behavior

The behaviour I'm seeing is as follows

```
==> linode.test-game-server: Failed to create event poller: failed to run pretask: failed to list events: [401] Your OAuth token is not authorized to use this endpoint.
==> linode.test-game-server: Provisioning step had errors: Running the cleanup provisioner, if present...
Build 'linode.test-game-server' errored after 4 minutes 16 seconds: Failed to create event poller: failed to run pretask: failed to list events: [401] Your OAuth token is not authorized to use this endpoint.
```

### Steps to Reproduce

Create an old api token on linode interface

### Error Output

==> linode.test-game-server: Failed to create event poller: failed to run pretask: failed to list events: [401] Your OAuth token is not authorized to use this endpoint.
==> linode.test-game-server: Provisioning step had errors: Running the cleanup provisioner, if present...
Build 'linode.test-game-server' errored after 4 minutes 16 seconds: Failed to create event poller: failed to run pretask: failed to list events: [401] Your OAuth token is not authorized to use this endpoint.

**Comment by lgarber-akamai** [comment]
Hello @d11ahirst! Sorry for the late response on this.

In `v1.1.0` we introduced an improved operation polling system that makes use of [Linode Events](https://github.com/linode/packer-plugin-linode/pull/83/files#diff-57ff5fb536e104beeca45aaacc220e25a2a2a199df7e0c72b4839ab3ecd13af1R25-R29) to more reliably wait for image creation. Because of this, this plugin now requires that your token have read permissions for events (`events:read_only`).

Could you validate that your token has read access to events?

**Comment by zliang-akamai** [comment]
Hi @d11ahirst,
Thank you for reporting the issue!
I hope @lgarber-akamai's response has solved your concern. I am closing this ticket, and please let us know if you still have any question.
